#!/bin/bash
docker build -t kmusic_bot_snapshot .
# check if script was run with -d flag
if [[ $1 == "-d" ]]; then
    docker run -d --name KMusic-v4.0.0-SNAPSHOT --restart always kmusic_bot_snapshot
else
    docker run kmusic_bot_snapshot
fi
