#!/bin/bash
docker build -t kmusic_bot_beta .
# check if script was run with -d flag
if [[ $1 == "-d" ]]; then
    docker run -d --name KMusic-v3.3.0-PREVIEW --restart always kmusic_bot_beta
else
    docker run kmusic_bot_beta
fi
