style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://git.kyleyannelli.com/kyle/KMusicBot
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
    #     - dep
    #     - chore
  commit_groups:
    # title_maps:
    #   feat: Features
    #   fix: Bug Fixes
    #   perf: Performance Improvements
    #   refactor: Code Refactoring
    #   dependency: Dependency changes
    #   chore: Grunt work
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE